FROM apache/superset:latest

USER root
RUN apt-get update && apt-get install -y gcc python3-dev libpq-dev && apt-get clean
USER superset

RUN pip install --no-cache-dir psycopg2

COPY ./dashboards/sales_dashboard_export.zip /app/dashboards/